### ISSUE TITLE
TypeError:__html.replace is not a function

### ISSUE THREAD

**Issue by jfozztino** [jonkemp/list-stylesheets#6]
I'm getting this error from list-stylesheets when running `gulp build`:

```
./project/node_modules/list-stylesheets/index.js:27
                __html = __html.replace(re, function (match) {
                                ^

TypeError: __html.replace is not a function
```

I haven't changed anything in my gulpfile and this error is occurring on both old projects and brand new ones.  Any idea what the issue might be?

**Comment by jonkemp** [comment]
Can you post the gulpfile or the task?

**Comment by jonkemp** [comment]
If it's coming from gulp-inline-css, make sure you have the latest version of the plugin.

**Comment by imakahn** [comment]
@jonkemp this is a deeper issue - the incoming _html is not being type-checked/casted to ensure it is a String. With older versions of gulp-inline-css it appears that down the line a Buffer is sent.

This code hasn't been changed for years up to this point, and it's a breaking change for those running legacy software that strictly declared gulp-inline-css 2.0 as the dependency and expect that to continue to behave as before. This module shouldn't be so tightly coupled to 3.x - people expect breaking changes when they move between major version numbers, but not within minors (and in this case, from no change in version number at all).

This could be fixed by either moving this new behavior to a list-stylesheets 2.x and updating the current versions of the higher modules to use it, or by adding in type-checking to enable it to continue working with the 2.x tree of gulp-inline-css.

**Comment by jfozztino** [comment]
Hey @jonkemp, we 'fixed' the issue and I forgot that I had an open question here!  

@kahnandrew Yes, the issue was that by the time .replace() was being called, __html was still a buffer.  We 'patched' the issue by simply wrapping that buffer in a String() call.

**Comment by jonkemp** [comment]
@kahnandrew there is no issue with gulp-inline-css 2.x. This issue happened when inline-css was updated but gulp-inline-css was still sending the buffer without converting it to a string. That issue has been fixed so to fix the issue, they just need to update the plugin.

Closing.
